name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Vercel Production Deployment
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_mwT3CZqCrQAg9EZWRszsdHFAkcEH/2o2JD0ZDcS
